<?php

namespace app\api\model;
use think\Model;

/**
 * 机器人
 */
class Userrobot extends Model
{
    protected $name = 'user_robot';

    public function getname(){
        $list = [
            "Vinestian",
            "Vivek",
            "Arti Sharma",
            "R K Sharma",
            "Sunil Pal",
            "Nishant Sandilya",
            "Gaurav sharma",
            "Swakil Hamim",
            "Sahareyar Nawab",
            "Rajsoni",
            "Shashank Vashishtha",
            "Somesh Sharma",
            "sunil deshmukh",
            "Asif Nawaz",
            "Sapan Jana",
            "Akhil",
            "Honey Watt",
            "Saurabh Saboo",
            "Rajpurohit Jayshree",
            "Sanjay R Kaushik",
            "Rahul Aghariya",
            "Mai Barickman",
            "bedram jangde",
            "Prasenjit Sur",
            "Ankit kumar",
            "Shiva Manohar R",
            "Pasha-Danish",
            "Ajay kumar Saini",
            "Vicky",
            "Monique Pontonio",
            "Pravat Sutar",
            "Muniraju N",
            "vidhu shekhar",
            "Lacey Castelli",
            "Kaur",
            "Mavis Dickerman",
            "Sharjeel Channa",
            "Mannat Sharma",
            "Rahesh",
            "fatima",
            "Sudipto Chakrabarty",
            "Nimit Chadha",
            "Rishabh",
            "shivam singh",
            "ankit tyagi",
            "DJP DJP",
            "Irfan Mushtaq",
            "Ilana Ferreri",
            "K kumar",
            "vijaykumar patil",
            "Apoorva Singh",
            "Akansha Singh",
            "Prashant rg",
            "Quiana Saraiva",
            "Ankita",
            "ardhan",
            "Galilea Platz",
            "Naman",
            "Ankit Rajput",
            "Maria Silvina Costa",
            "Keyur Patel",
            "Ashutosh Dhamankar",
            "Anusha Pai",
            "Hameed Xehri",
            "Rajesh",
            "Himsagar",
            "Dapinder Mann",
            "jeet",
            "Priyanshu",
            "Shriraj Patil",
            "Sanjeev Sharma",
            "Sachin Kumar",
            "Dattanand Kamat",
            "Zeeshan",
            "Tapan Chakravarty",
            "Tila",
            "Killing Devil",
            "Ramanathan Ramaswamy",
            "tanya",
            "Kapil Raj Singh",
            "Deep",
            "Pranamipradip",
            "Reet",
            "Dahlia Maerz",
            "Anand Kumar Dubey",
            "Kumar",
            "Naresh Agrawal",
            "Lia Herridge",
            "weddingforum",
            "Shubham Gupta",
            "Vikas Saxena",
            "JAYRAJ",
            "vinay sharma",
            "Kavi Krishnan",
            "Amar6798",
            "Amit",
            "Suraj Rawat",
            "Aprameya Bhol",
            "indian1st",
            "Naresh Singh",
            "Gayu",
            "Bhavesh Parmar",
            "Sasikumar",
            "Vineet Kumar Yadav",
            "Kunal Kulthe",
            "Mandeep Singh deep Rakim R7",
            "Aakruti Singh",
            "Taylor Hilbert",
            "Ankita_ali",
            "Dhoni Official",
            "Aairani Mishra",
            "JITENDRA CHAUDHARY",
            "Natraj Pithani",
            "Amrit Kunwar Singh",
            "Prabhu Rathore",
            "Praful Karkera",
            "Hisoka",
            "SAGAR SUTHAR",
            "Dof James",
            "shaheeda fernando",
            "Alishia Largent",
            "Hilda Rebecca",
            "Sibansh Mohanty",
            "KARAN SINGH",
            "Audrey Blanke",
            "Sheikh Mujahid",
            "Mayank Dixit",
            "Rashi Chopra",
            "Dara Luedi",
            "Dev Jaiswal",
            "Gagandeep khare",
            "Sachin Rotwal",
            "Vijay Kumar",
            "Rahul Yadav",
            "Rk Jais",
            "Mannu Jha",
            "Priyamvada",
            "Kp Kaliya",
            "Shivam Kumar",
            "Sourabh Baghel",
            "Johnetta Samele",
            "Praburam Srinivasan",
            "Rakeshtailee",
            "Upendrasinh vaghela",
            "Rupesh Mishra",
            "Deepak",
            "Zohaib Warraich",
            "Prem babu M",
            "Shalonda Car",
            "Saurabh Yadav",
            "maverick",
            "Jain Auto Agencis",
            "Megha Das",
            "Faisal",
            "Shahid A",
            "Ankit Singh",
            "Hadia Mujahiad",
            "Samratsinh",
            "Rajesh Tiwari",
            "Pooja Abheer",
            "Rprabhu",
            "Nikhil Rai",
            "Bhuwan Joshi",
            "ankur bhardwaj",
            "NAVNIT KUMAR",
            "Hamara pyara desh",
            "Tuman Boruah",
            "Saurabh Kant Yadav",
            "soumo",
            "Parmeshwar Bawa",
            "Adv Hitesh Jain",
            "Pradeep Patel",
            "Shyam Sundar",
            "mallika",
            "Malia Slaby",
            "Monti Pal",
            "Live_Bold Devil",
            "Shishir",
            "Raj Ponnappa",
            "Amrita Verma",
            "Ram Naragoni",
            "Poonam Manik",
            "Shahid Basharat",
            "Marleen Honour",
            "Hakim Mudasir Wani",
            "Roseline",
            "Suman Kumar Dhara",
            "Keshav Malhotra",
            "Amit Poddar",
            "Joan Auld",
            "Mehul",
            "Kelvin Philips",
            "manak jain",
            "Bhim Rai",
            "Daniël van Duijn",
            "VISHNU USHA",
            "Rashid Khan",
            "Leoma Sivay",
            "Rohit Jaiswal",
            "Jhalak Malhotra",
            "Ravi Prakash",
            "Sreevatchan S",
            "Akhlaque Ansari",
            "Ritu Singh Gour",
            "Atul Purohit",
            "Denita Rinehart",
            "Rohit Mishra",
            "nikhil",
            "MUKUL K",
            "Ranjit Singh",
            "Sagar Pardhekar",
            "Izaz khan",
            "Reham Sheikh",
            "Diana Rivas",
            "Gaurav Kumar",
            "Amod Ranade",
            "Karajan",
            "ravi chhimwal",
            "Jatin kamdar",
            "Anuj Patel",
            "Rana",
            "Situ Pandey",
            "Ritu Goyal",
            "Sunny Kundlé",
            "Javed Beigh",
            "sanjeev",
            "Krunal Shah",
            "Simran Singh",
            "Elfreda Padron",
            "Aniket Singh Chauhan",
            "Manish Goyal",
            "Sadichha Pattnaik",
            "IndianLady",
            "Liberty Caracciola",
            "Amit Paul",
            "J N Govind Ojha",
            "Vishal Goswami",
            "chandan kumar",
            "Harsh Chugh",
            "Lola Talentino",
            "Somya Bahukhandi",
            "Kaiiashuhai",
            "Ishrat Ali",
            "Krishnakant",
            "Awais Ahmad",
            "Katy Cammarn",
            "Sumit Puskar",
            "Harshita upadhyay",
            "Vipin Singh",
            "Meenakshi",
            "Cornelia Needham",
            "Floretta Hemond",
            "lalit kishor",
            "Shan Orduna",
            "Rajnish Manhas",
            "Tamesha Schuh",
            "Satish",
            "Louann Linares",
            "Ddhameliya",
            "Shailesh",
            "priyankanaskar",
            "Safikansari",
            "Manish",
            "Shilpa Trivedi",
            "Hemant Kumar",
            "Mehtab",
            "Setsuko Chevere",
            "Manish Kumar Jha",
            "Ninad Jadhav",
            "Yash Khangarot",
            "Indian Bro",
            "Chaitanya",
            "Tiffany Kuh",
            "Ayat Chiapetti",
            "Md Aakib",
            "Voice Of Jains",
            "Utibe Ekong",
            "Das Boot",
            "Elisa Thruman",
            "BHUVNESH  AGRAWAL",
            "Tabrez Zafar",
            "Nirav Kanojiya",
            "Unnikrishnan",
            "Vinay Singh",
            "Rajender Galgat",
            "princess",
            "AKSHAYA",
            "Gejja Ram Valmiki",
            "Vijay Pawar",
            "Uzmarizvi",
            "SAURAV RAJ",
            "Heart Killer",
            "om yadav",
            "Sloane Guley",
            "Contessa Houf",
            "lavaraja",
            "Robin Kasowski",
            "Anil Gurjar, Ph",
            "Labisha shrestha",
            "DarkSparrow",
            "Saroj Kumar Mishra",
            "Vineet Shukla",
            "santosh gouda",
            "Prabha",
            "Praveen Singh",
            "Support Nupur Sharma, Sanatani_Sanghi",
            "Bethann Waage",
            "Vihu",
            "Anonymous",
            "Gujjar J",
            "shubham mishra",
            "Mahadev Rakte",
            "Sakshi Kotwal",
            "Jamal Boloch",
            "Sanju baba",
            "Bonny Zega",
            "shashipriya",
            "Mandeep Singh Vinaik",
            "Mujtaba",
            "Dev tripathi",
            "Nidhi Rohit Sharma",
            "Shivani",
            "Ihsan Wazir",
            "Naresh",
            "Rahul Chakraborty",
            "Sunny Gautam",
            "Aakriti Sharma",
            "Rohit Binjola",
            "Kavita Marathe",
            "Sachin Suryawanshi",
            "Pradeep Kashyap",
            "Nagarjuna",
            "Mussa",
            "Neha Vaish",
            "Nobir Ali Sha",
            "Belen Alcat",
            "mokawat",
            "Don Wick",
            "Rohit Yadav",
            "sinku",
            "Whistling Blue",
            "OMARAM HINDU",
            "Suraj Kewat",
            "Vandana Sharma",
            "K Pritam Singh",
            "alok mishra",
            "ajay shekhawat",
            "Noreen Linkhart",
            "Manisha Bhasin, corporate chef",
            "Nayal",
            "Abhijeet sen",
            "Swetalina Mohapatra",
            "Audrie Petrik",
            "Manoj Singh",
            "Vicky Srivastava",
            "Tarunendra Dwivedi",
            "Amit Kumar",
            "Shahid Ali",
            "Vande Matram",
            "Deepak Arora",
            "Zain khan",
            "Ranjan yadav",
            "Sharma",
            "Dipak Mariya",
            "Saurav S",
            "Srikanth Bi",
            "Uday Kumar Sharma",
            "Ravi Kiran Reddy",
            "daniel-gnu",
            "Rama Tiwari",
            "Narain Das Bheel",
            "Muni",
            "Vinesh Rawal",
            "mythra",
            "Sahil",
            "rohan sanyal",
            "prasad",
            "Valerie Gibson",
            "Manish Sharma",
            "Harmeet Kaur",
            "Viktor Belmont",
            "Aadikayapak",
            "Ricky",
            "Suraj Sharma",
            "Pankaj Papanai",
            "Ashvin",
            "Piyush chavan",
            "Rakesh Kumar Verma",
            "altaf khan",
            "TAPENDRA",
            "Ashish Nautiyal",
            "Destiny Bolender",
            "Kamlesh Chopra",
            "Irshad",
            "Jayesh Nai",
            "Ubaida Abul Hasanat",
            "Cinthia Avers",
            "Shivendra",
            "Hansraj vaidya",
            "Pradeepsingh Rajput",
            "Prashant Yadav",
            "Hasan Rizvi",
            "Shara Ashraf",
            "Deeptiman Tiwari",
            "Mir Joziya",
            "Laksraj",
            "Ihteram sadiq",
            "Suvam Ghosh",
            "Hitesh R Singh",
            "Jay Dhall",
            "ruchika",
            "Yuvraj Akhiya",
            "Mukund Telesystem",
            "Siba_Shaw",
            "Dharmrakshak",
            "Tilly Lampp",
            "KK Mishra",
            "Monika",
            "Monidipa Bose",
            "Pabitra",
            "Sharafat Khan",
            "girdhar charan",
            "Emon Mukherjee",
            "hiren shekhada",
            "Amit Singh",
            "Ayaz",
            "Vipul Rai",
            "Manoj Kumar",
            "Mahajan",
            "Alok Ranjan Pathak",
            "bramhastra",
            "Sanjeev Bhatnagar",
            "Naureen",
            "SURAJ TIWARI",
            "Ali Hasnain",
            "Jainul ansari",
            "neha choudhary",
            "ajoy guin",
            "Yash",
            "Ranjit Thakur",
            "Mohit kumar",
            "Chandra Chatterjee",
            "Prantick Gope",
            "Sarjeet Chauhan",
            "Anand Kumar",
            "Satyam Singh",
            "Devendra Kumar",
            "Naina Agrahar",
            "SuppeR Villian",
            "Jyoti jaiswal bjp",
            "the Hindu",
            "Sakchi Singh",
            "rajendra",
            "Ketan Brahmbhatt",
            "Naveen Singh",
            "Suraj Singh",
            "Phoebe Notice",
            "Manu Nanda Kumar",
            "Lo Aaya",
            "Shammo Dutta",
            "Lavenia Jeansonne",
            "Guru",
            "Truth speaker",
            "Kayyum Khan",
            "Deep Debnath",
            "Krishna"
        ];
        return $list;
    }
}
